default_agent: orchestrator
agents:
  orchestrator:
    name: orchestrator
    language: python
    node_version: '20'
    entrypoint: /Users/viohan/Desktop/BankAgent/OrchestratorAgent/orchestrator.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/viohan/Desktop/BankAgent/OrchestratorAgent
    aws:
      execution_role: arn:aws:iam::543486084696:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-11376b7e2a
      execution_role_auto_create: false
      account: '543486084696'
      region: ap-southeast-2
      ecr_repository: 543486084696.dkr.ecr.ap-southeast-2.amazonaws.com/bedrock-agentcore-orchestrator
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: orchestrator-gz1xM3HQRK
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-2:543486084696:runtime/orchestrator-gz1xM3HQRK
      agent_session_id: fc08df9b-142c-4327-a2d1-f111e3b36507
    codebuild:
      project_name: bedrock-agentcore-orchestrator-builder
      execution_role: arn:aws:iam::543486084696:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-2-11376b7e2a
      source_bucket: bedrock-agentcore-codebuild-sources-543486084696-ap-southeast-2
    memory:
      mode: STM_ONLY
      memory_id: orchestrator_mem-mkQhlEF44E
      memory_arn: arn:aws:bedrock-agentcore:ap-southeast-2:543486084696:memory/orchestrator_mem-mkQhlEF44E
      memory_name: orchestrator_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
